name: Test generate-metadata-action

on:
  push

jobs:
  action-run:
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.action-run.outputs.filepath }}
    steps:
      - name: 'Checkout directory'
        uses: actions/checkout@v2
      - name: Generate metadata file
        id: generate_metadata
        uses: ./
        with:
          product: test-product-name
          version: 0.0.0

      - uses: actions/upload-artifact@v2
        with:
          name: metadata.json
          path: ${{ steps.generate_metadata.outputs.filepath }}
